<?php

use Ajrc\Helper\Sessions;

// SEO : SEARCH ENGINE OPTIMIZATE ----
$title = "Chokoart - o BUSCADOR mais atraente que você verá e encontrará!";
$description = $title." Chocolates de vários sabores para os mais refinados gostos!";
$url_redirect = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
//----

require_once("../templates/public/header.php");
require_once("../templates/public/topo.php");

?>

<!-- Main Content -->
<div class="container mt-3 mb-3">
      <div class="row gutters-3">

        

        <div class="col-12">

          <!-- Shop Toolbar -->
          <div class="card mb-3">
            <div class="card-body d-flex justify-content-end align-items-center py-2">
              <ol class="breadcrumb d-none d-md-flex p-0 mb-0 mr-auto">
                <li class="breadcrumb-item"><a href="./">Página Principal</a></li>
                <li class="breadcrumb-item"><a href="#">Busquei por</a></li>
                <li class="breadcrumb-item active" aria-current="page"><span class="h5 bold" style="color:#e83e8c"><i><?php echo trim($_POST["termo_buscado"]); ?></i></span></li>
              </ol>
                <span class="text-muted mr-1">Compartilhe:</span>
                <a href="https://www.facebook.com/sharer.php?u=<?php echo $url_redirect; ?>" class="btn btn-icon rounded-pill btn-sm btn-outline-primary ml-1" data-toggle="tooltip" target="_blank" title="no Facebook"><i data-feather="facebook"></i></a>
                <a href="http://twitter.com/intent/tweet?text=<?php echo $title;?>&url=<?php echo $url_redirect; ?>&via=@chokoart.com" class="btn btn-icon rounded-pill btn-sm btn-outline-primary ml-1" data-toggle="tooltip" target="_blank" title="no Twitter"><i data-feather="twitter"></i></i></a>
            </div>
          </div>
          <!-- /Shop Toolbar -->

          <!-- Shop Grid -->
            <?php 
                //----| LISTA DOS PRODUTOS RETORNADOS PELO BUSCADOR |------
                \Ajrc\Model\Buscador::ListAll( $_POST["termo_buscado"] );
                //----
            ?>
          <!-- /Shop Grid -->

        </div>
      </div>
    </div>
    <!-- /Main Content -->

   

    


<!-- Footer -->
<?php 
require_once("../templates/public/footer.php"); 
?>
<!-- /Footer -->

    <script src="plugins/jquery/jquery.min.js"></script>
    <script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="plugins/feather-icons/feather.min.js"></script>
    <script src="plugins/metismenu/metisMenu.min.js"></script>
    <script src="plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="plugins/swiper/swiper.min.js"></script>
    <script src="plugins/nouislider/nouislider.min.js"></script>
    <script src="plugins/photoswipe/photoswipe.min.js"></script>
    <script src="plugins/photoswipe/photoswipe-ui-default.min.js"></script>
    <script src="plugins/noty/noty.min.js"></script>
    <script src="dist/js/script.min.js"></script>
    <script src="js/produto.js"></script>
    <script>
    $(function () {

      App.rating()
      App.atwDemo()
      App.colorOption()
      App.rating()
      App.quickviewDemo()

      var filter = {
        categories: function () {
          $('.list-tree').metisMenu()
        }
      }


     

      <?php
        if(Sessions::UserID()!="") { 
            echo "WishList.Persistence('../add-whislist');"; 
        }
        ?>

    })
    </script>




</body>
</html>
