

    <?php
      
      require_once("../templates/public/header.php");
      require_once("../templates/public/topo.php");

      $msg = null;
      if(array_key_exists("msg",$_GET)){
        $msg = "<h4 style='text-align:center'>" . trim($_GET["msg"]) . "</4>";
      }

    ?>

    <!-- Main Content -->
    <div class="container my-3 my-sm-5">

      <!-- Login & Register Row -->
      <div class="row justify-content-center" id="row-login">
        <div class="col-sm-10 col-md-11 col-lg-9 col-xl-8">
          <div class="card card-login">
            <div class="card-body">
              <div class="row">

                <!-- Login Form -->
                <div class="col-md-6 col-login">
                  <form class="form-style-1" method="POST">
                    <div class="form-group text-center mb-2">
                      <h2 class="bold mb-0">Login</h2>
                      <em>em sua conta</em>
                      <?php echo $msg; ?>
                    </div>
                    <div class="form-group">
                      <span class="input-icon">
                        <i data-feather="mail"></i>
                        <input type="email" name="email" class="form-control" placeholder="Digite seu E-MAIL" required>
                      </span>
                    </div>
                    <div class="form-group">
                      <span class="input-icon">
                        <i data-feather="lock"></i>
                        <input type="password" name="password" class="form-control" placeholder="Digite sua SENHA" required>
                      </span>
                    </div>
                    <div class="form-group d-flex justify-content-between">
                      <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="loginRemember">
                        <label class="custom-control-label" for="loginRemember">Permanecer logado</label>
                      </div>
                      <u><a href="#" class="text-primary small reset">Esqueceu sua senha ?</a></u>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">LOGIN</button>
                  </form>
                </div>
                <!-- /Login Form -->

                <span class="or-divider">OU</span>

                <!-- Register Form -->
                <div class="col-md-6 col-register">
                  <form class="form-style-2">
                    <div class="form-group text-center">
                      <h2 class="bold">Registro</h2>
                    </div>
                    <div class="form-group">
                      <span class="input-icon">
                        <i data-feather="mail"></i>
                        <input type="email" class="form-control" placeholder="E-mail">
                      </span>
                    </div>
                    <div class="form-group">
                      <span class="input-icon">
                        <i data-feather="lock"></i>
                        <input type="password" class="form-control" placeholder="Senha">
                      </span>
                    </div>
                    <div class="form-group">
                      <span class="input-icon">
                        <i data-feather="lock"></i>
                        <input type="password" class="form-control" placeholder="Confirme a Senha">
                      </span>
                    </div>
                    <button type="button" class="btn btn-outline-primary btn-block">REGISTRAR-SE</button>
                  </form>
                </div>
                <!-- /Register Form -->

              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /Login & Register Row -->

      <!-- Reset Password -->
      <div class="row justify-content-center" id="row-reset" hidden>
        <div class="col-sm-8 col-md-6 col-lg-5 col-xl-4">
          <div class="card">
            <div class="card-body">
              <form class="form-style-1">
                <div class="form-group text-center">
                  <h2 class="bold">Esqueceu sua senha?</h2>
                  <em>entre com o e-mail registrado para receber mais intruções</em>
                </div>
                <div class="form-group">
                  <span class="input-icon">
                    <i data-feather="mail"></i>
                    <input type="email" class="form-control" placeholder="Seu E-MAIL ">
                  </span>
                </div>
                <button type="button" class="btn btn-danger btn-block reset-done">SOLICITAR NOVA SENHA</button>
              </form>
              <hr>
              <button class="btn btn-light btn-sm login"><i data-feather="arrow-left"></i> Voltar</button>
            </div>
          </div>
        </div>
      </div>
      <!-- /Reset Password -->


    </div>
    <!-- /Main Content -->

    <!-- Footer -->
    <div class="footer">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-sm-6 col-lg-3 text-center px-3">
            <h5 class="bold">SUBSCRIBE</h5>
            <p>and get <strong class="text-primary">10% discount</strong></p>
            <form>
              <div class="form-group">
                <input type="email" class="form-control rounded-pill text-center" placeholder="Enter your email">
              </div>
              <button type="button" class="btn btn-primary btn-block rounded-pill">SUBSCRIBE</button>
            </form>
          </div>
          <div class="col-6 col-lg-3">
            <h6 class="bold">Customer Service</h6>
            <div class="list-group list-group-flush list-group-no-border list-group-sm">
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Help Center</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">How to buy</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Delivery</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">How to return</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Payment Method</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Shipping Method</a>
            </div>
          </div>
          <div class="col-6 col-lg-3">
            <h6 class="bold">Mimity</h6>
            <div class="list-group list-group-flush list-group-no-border list-group-sm">
              <a href="about.html" class="list-group-item list-group-item-action">About Us</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Terms and Conditions</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Privacy Policy</a>
              <a href="faq.html" class="list-group-item list-group-item-action">FAQs</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Our Story</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Services</a>
            </div>
          </div>
          <div class="col-sm-6 col-lg-3">
            <h6 class="bold">Download The App</h6>
            <a href="javascript:void(0)" class="download-app">
              <div class="media">
                <img src="/img/app/google-play.svg" alt="Google Play Logo" height="30">
                <div class="media-body">
                  <small>Get it on</small>
                  <h5>Google Play</h5>
                </div>
              </div>
            </a>
            <a href="javascript:void(0)" class="download-app">
              <div class="media">
                <img src="/img/app/apple.svg" alt="Apple Logo" height="30">
                <div class="media-body">
                  <small>Download on the</small>
                  <h5>App Store</h5>
                </div>
              </div>
            </a>
            <a href="javascript:void(0)" class="download-app">
              <div class="media">
                <img src="/img/app/windows.svg" alt="Windows Logo" height="30">
                <div class="media-body">
                  <small>Get it from</small>
                  <h5>Microsoft Store</h5>
                </div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="copyright">Copyright © 2019 Mimity All right reserved</div>
    <!-- /Footer -->


    <!--Menu Modal -->
    <div class="modal modal-left modal-menu" id="menuModal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header shadow">
            <a class="h5 mb-0 d-flex align-items-center" href="index.html">
              <img src="/img/logo.svg" alt="Mimity" class="mr-3">
              <strong>Mimity</strong>
            </a>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body shadow">
            <ul class="menu" id="menu">
              <li class="no-sub"><a href="index.html"><i data-feather="home"></i> Home</a></li>
              <li>
                <a href="#" class="has-arrow"><i data-feather="shopping-bag"></i> Shop</a>
                <ul>
                  <li><a href="shop-categories.html">Shop Categories</a></li>
                  <li><a href="shop-grid.html">Shop Grid</a></li>
                  <li><a href="shop-list.html">Shop List</a></li>
                  <li><a href="shop-single.html">Single Product</a></li>
                  <li><a href="shop-single2.html">Single Product v2</a></li>
                  <li><a href="cart.html">Cart</a></li>
                  <li><a href="shipping.html">Checkout</a></li>
                  <li>
                    <a href="#">Submenu</a>
                    <ul>
                      <li><a href="javascript:void(0)">item #1</a></li>
                      <li><a href="javascript:void(0)">item #2</a></li>
                      <li><a href="javascript:void(0)">item #3</a></li>
                    </ul>
                  </li>
                </ul>
              </li>
              <li>
                <a href="#" class="has-arrow"><i data-feather="rss"></i> Blog</a>
                <ul>
                  <li><a href="blog-grid.html">Post Grid</a></li>
                  <li><a href="blog-list.html">Post List</a></li>
                  <li><a href="blog-single.html">Single Post</a></li>
                </ul>
              </li>
              <li>
                <a href="#" class="has-arrow"><i data-feather="user"></i> Account</a>
                <ul>
                  <li class="mm-active"><a href="account-login.html">Login / Register</a></li>
                  <li><a href="account-profile.html">Profile Page</a></li>
                  <li><a href="account-orders.html">Orders List</a></li>
                  <li><a href="account-order-detail.html">Order Detail</a></li>
                  <li><a href="account-wishlist.html" class="has-badge">Wishlist <span class="badge rounded badge-primary">2</span></a></li>
                  <li><a href="account-address.html">Address</a></li>
                </ul>
              </li>
              <li>
                <a href="#" class="has-arrow"><i data-feather="file"></i> Pages</a>
                <ul>
                  <li><a href="about.html">About Us</a></li>
                  <li><a href="contact.html">Contact Us</a></li>
                  <li><a href="compare.html">Compare</a></li>
                  <li><a href="faq.html">Help / FAQ</a></li>
                  <li><a href="404.html">404 Not Found</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- /Menu Modal -->


    <!-- REQUIRED JS  -->
    <script src="/plugins/jquery/jquery.min.js"></script>
    <script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/plugins/feather-icons/feather.min.js"></script>
    <script src="/plugins/metismenu/metisMenu.min.js"></script>
    <script src="/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>

    <!-- Mimity JS  -->
    <script src="/dist/js/script.min.js"></script>

    <script>
    $(function () {

      // Show reset password form
      $('.reset').click(function (event) {
        $('#row-login').attr('hidden', true)
        $('#row-reset').attr('hidden', false)
        event.preventDefault()
      })

      // Show login form
      $('.login').click(function (event) {
        $('#row-login').attr('hidden', false)
        $('#row-reset').attr('hidden', true)
        $('#row-reset-done').attr('hidden', true)
      })

      // Show reset password done message (demo purpose only)
      $('.reset-done').click(function (event) {
        $('#row-reset-done').attr('hidden', false)
        $('#row-reset').attr('hidden', true)
      })

    })
    </script>

  </body>
</html>