
    <?php

    use Ajrc\Helper\Sessions;
    use Ajrc\Model\Usuario;
  
    $u = Usuario::List(Sessions::UserID());
    
    if(empty($u)){
      echo "Usuário inexistente!";
      exit();
    }
    
    $check_excluir_foto = null;
    $foto_usuario = null;
    $pasta_imagens = "img/usuarios/";
    foreach (glob($pasta_imagens . $u->id."_1.*") as $foto) {
        $foto_usuario = "<img src='".$foto."'>";
        $check_excluir_foto =  '<br><div class="checkbox checkbox-success checkbox-inline">
                                    <input tabindex="18" name="excluir_foto" id="excluir_foto" value="'.$foto.'" type="checkbox">
                                    <label for="excluir_foto">Excluir a foto atual?</label>
                                </div>';
    }

    $sexo = null;
    $sexos = [""=>"Selecione", "M"=>"Masculino", "F"=>"Feminino"];
    foreach($sexos as $key=>$value){
        $sel = ($u->sexo==$key)?" selected='selected'":null;
        $sexo.= "<option value='".$key."'".$sel.">".$value."</option>";
    }
    

    $required = " required ";
    
      
    require_once("../templates/public/header.php");
    require_once("../templates/public/topo.php");

    ?>

    <!-- Main Content -->
    <div class="container my-3">
      <div class="row">

        <div class="col-md-4 col-lg-3">
          <div class="card">
            <div class="card-body text-center">
              <img src="<?php echo Sessions::UserPhoto(); ?>" width="80" height="80" alt="Foto de Adair" class="rounded-circle mb-3">
              <h5 class="bold mb-0"><?php echo Sessions::UserName(); ?></h5>
              <small class="counter">Cliente desde <?php echo Sessions::UserSince(); ?></small>
              <hr>
              <div class="roboto-condensed bold" data-toggle="tooltip" title="You currently have 1,113 Points to spend.">
                <i data-feather="award" class="text-warning"></i> Pontos: 1113</div>
            </div>
            <div class="list-group list-group-flush">
              <a href="#" class="list-group-item list-group-item-action active"><i data-feather="user" class="mr-3"></i> Seus Dados</a>
              <a href="#account-orders" class="list-group-item list-group-item-action"><i data-feather="shopping-bag" class="mr-3"></i> Pedidos</a>
              <a href="#account-wishlist" class="list-group-item has-badge list-group-item-action"><i data-feather="heart" class="mr-3"></i> Lista de Desejos <span class="badge rounded badge-primary">2</span></a>
              <a href="./account-logout" class="list-group-item list-group-item-action text-danger"><i data-feather="log-out" class="mr-3"></i> Logout</a>
            </div>
          </div>
        </div>

        <div class="col mt-3 mt-md-0">
          <div class="card">
            <div class="card-body">
              <h3>Seus dados</h3><hr>
              <?php 
              if(array_key_exists("status",$_GET))
              {
                $tipomsg = "danger";
                $txtmsg = "<strong>Ops ... Ocorreu algum problema!</strong> Por favor, tente mais tarde novamente";
                if($_GET["status"]=="1")
                {
                  $tipomsg = "success";
                  $txtmsg = "<strong>Seus dados foram ATUALIZADOS</strong> com sucesso! ";
                }

                echo "<div class=\"alert alert-".$tipomsg."\" role=\"alert\">
                        ".$txtmsg." <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">
                        <span aria-hidden=\"true\">&times;</span>
                        </button>
                    </div><script>setTimeout(function(){ $(\".alert\").alert(\"close\"); },5000);</script>";
              } 
              ?>
              <form class="form form-style-1" data-toggle="validator" data-disable="false" role="form" method="POST" action="./usuarios" enctype="multipart/form-data">
                <input type="hidden" name="operacao" value="public">
                <input type="hidden" name="id" id="id" value="<?php echo $u->id; ?>">
                <input type="hidden" name="cliente" id="cliente" value="1">
                <input type="hidden" name="status" id="status" value="A">
                <div class="container-fluid float-left">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-6">

                                    <div class="form-group">
                                        <label for="nome">Nome</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-user"></i></div>
                                        <input tabindex="1" data-error="Campo de preenchimento obrigatório!" class="form-control" type="text" name="nome" id="nome" value="<?php echo $u->nome; ?>" <?php echo $required; ?>>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="login">Login</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
                                        <input tabindex="3"  data-error="Campo de preenchimento obrigatório!" class="form-control" type="text" name="login" id="login" value="<?php echo $u->login; ?>" <?php echo $required; ?>>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="sexo">Sexo</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-intersex"></i></div>
                                        <select tabindex="5"  data-error="Campo de preenchimento obrigatório!" class="form-control selectpicker" name="sexo" id="sexo" <?php echo $required; ?>>
                                            <?php echo $sexo;?>
                                        </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="cep">CEP</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-address-card"></i></div>
                                        <input tabindex="7"  data-error="Campo de preenchimento obrigatório!" class="form-control" type="text" name="cep" id="cep" value="<?php echo $u->cep; ?>" onkeypress="$(this).mask('00.000-000')" <?php echo $required; ?>>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="cidade">Cidade</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-address-card"></i></div>
                                        <input tabindex="9"  data-error="Campo de preenchimento obrigatório!" class="form-control" type="text" name="cidade" id="cidade" value="<?php echo $u->cidade; ?>" <?php echo $required; ?>>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="endereco">Endereço</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-address-card"></i></div>
                                        <input tabindex="11"  data-error="Campo de preenchimento obrigatório!" class="form-control" type="text" name="endereco" id="endereco" value="<?php echo $u->endereco; ?>" <?php echo $required; ?>>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="numero">Número</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-address-card"></i></div>
                                        <input tabindex="13"  data-error="Campo de preenchimento obrigatório!" class="form-control" type="text" name="numero" id="numero" value="<?php echo $u->numero; ?>" <?php echo $required; ?>>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="telefone">Telefone</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-phone"></i></div>
                                        <input tabindex="15"  class="form-control" type="text" name="telefone" id="telefone" value="<?php echo $u->telefone; ?>" onkeypress="$(this).mask('(00) 0000-0000')">
                                        </div>
                                    </div>

                                    <div class="form-group" style="margin-top:20px;text-align:center">
                                        <label>
                                            <label for="foto"><div class="fa fa-image"></div> Escolha a foto do seu perfil:</label>
                                            <input tabindex="17"  type="file" class="form-control-file" name="foto" id="foto">
                                        </label>
                                    </div>

                                </div>
                                <div class="col-md-6">

                                    <div class="form-group">
                                        <label for="email">E-mail</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
                                        <input tabindex="2"  data-error="Campo de preenchimento obrigatório!" class="form-control" type="email" name="email" id="email" value="<?php echo $u->email; ?>" <?php echo $required; ?>>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="senha">Senha</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-key"></i></div>
                                        <input tabindex="4"  class="form-control" name="senha" id="senha" type="password" placeholder="Senha">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="data_nascto">Data de Nascimento</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-calendar"></i></div>
                                        <input tabindex="6"  data-error="Campo de preenchimento obrigatório!" class="form-control" name="data_nascto" id="data_nascto" type="date" value="<?php echo $u->data_nascto; ?>" <?php echo $required; ?>>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="cpf">CPF</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-user"></i></div>
                                        <input tabindex="8"  data-error="Campo de preenchimento obrigatório!" class="form-control" type="text" name="cpf" id="cpf" value="<?php echo $u->cpf; ?>" <?php echo $required; ?>>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="estado">Estado/UF</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-address-card"></i></div>
                                        <input tabindex="10"  data-error="Campo de preenchimento obrigatório!" class="form-control" type="text" name="estado" id="estado" value="<?php echo $u->estado; ?>" maxlength="2" <?php echo $required; ?>>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="bairro">Bairro</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-address-card"></i></div>
                                        <input tabindex="12"  data-error="Campo de preenchimento obrigatório!" class="form-control" type="text" name="bairro" id="bairro" value="<?php echo $u->bairro; ?>" <?php echo $required; ?>>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="complemento">Complemento</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-address-card"></i></div>
                                        <input tabindex="14"  class="form-control" type="text" name="complemento" id="complemento" value="<?php echo $u->complemento; ?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="celular">Celular</label>
                                        <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-mobile"></i></div>
                                        <input tabindex="16"  class="form-control" type="text" name="celular" id="celular" onkeypress="$(this).mask('(00) 00000-0000')" value="<?php echo $u->celular; ?>">
                                        </div>
                                    </div>
                                    
                                    <div class="col-xs-12  foto_usuario" style="text-align:center">
                                        <?php echo $foto_usuario . $check_excluir_foto; ?>
                                    </div>

                                </div>
                                
                                <div class="col-md-12" style="padding:10px">
                                    <button class="btn btn-success btn-block">SALVAR</button>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
                
            </form>


              <!--
              <form class="form-style-1">
                <div class="form-row">
                  <div class="form-group col-sm-6">
                    <label for="profileFirstName">First Name</label>
                    <input type="text" class="form-control" id="profileFirstName" value="John">
                  </div>
                  <div class="form-group col-sm-6">
                    <label for="profileLastName">Last Name</label>
                    <input type="text" class="form-control" id="profileLastName" value="Thor">
                  </div>
                  <div class="form-group col-sm-6">
                    <label for="profileEmail">Email address</label>
                    <input type="email" class="form-control" id="profileEmail" value="john.thor@example.com">
                  </div>
                  <div class="form-group col-sm-6">
                    <label for="profilePhone">Phone Number</label>
                    <input type="text" class="form-control" id="profilePhone" value="1-787-376-1552">
                  </div>
                  <div class="form-group col-sm-6">
                    <label for="profileNewPassword">New Password</label>
                    <input type="password" class="form-control" id="profileNewPassword">
                  </div>
                  <div class="form-group col-sm-6">
                    <label for="profileConfirmPassword">Confirm Password</label>
                    <input type="password" class="form-control" id="profileConfirmPassword">
                  </div>
                  <div class="form-group col-12">
                    <button type="button" class="btn btn-primary">UPDATE PROFILE</button>
                  </div>
                </div>
              </form>
              -->

            </div>
          </div>
        </div>

      </div>
    </div>
    <!-- /Main Content -->


    <!-- Footer -->
    <div class="footer">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-sm-6 col-lg-3 text-center px-3">
            <h5 class="bold">SUBSCRIBE</h5>
            <p>and get <strong class="text-primary">10% discount</strong></p>
            <form>
              <div class="form-group">
                <input type="email" class="form-control rounded-pill text-center" placeholder="Enter your email">
              </div>
              <button type="button" class="btn btn-primary btn-block rounded-pill">SUBSCRIBE</button>
            </form>
          </div>
          <div class="col-6 col-lg-3">
            <h6 class="bold">Customer Service</h6>
            <div class="list-group list-group-flush list-group-no-border list-group-sm">
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Help Center</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">How to buy</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Delivery</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">How to return</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Payment Method</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Shipping Method</a>
            </div>
          </div>
          <div class="col-6 col-lg-3">
            <h6 class="bold">Mimity</h6>
            <div class="list-group list-group-flush list-group-no-border list-group-sm">
              <a href="about.html" class="list-group-item list-group-item-action">About Us</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Terms and Conditions</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Privacy Policy</a>
              <a href="faq.html" class="list-group-item list-group-item-action">FAQs</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Our Story</a>
              <a href="javascript:void(0)" class="list-group-item list-group-item-action">Services</a>
            </div>
          </div>
          <div class="col-sm-6 col-lg-3">
            <h6 class="bold">Download The App</h6>
            <a href="javascript:void(0)" class="download-app">
              <div class="media">
                <img src="/img/app/google-play.svg" alt="Google Play Logo" height="30">
                <div class="media-body">
                  <small>Get it on</small>
                  <h5>Google Play</h5>
                </div>
              </div>
            </a>
            <a href="javascript:void(0)" class="download-app">
              <div class="media">
                <img src="/img/app/apple.svg" alt="Apple Logo" height="30">
                <div class="media-body">
                  <small>Download on the</small>
                  <h5>App Store</h5>
                </div>
              </div>
            </a>
            <a href="javascript:void(0)" class="download-app">
              <div class="media">
                <img src="/img/app/windows.svg" alt="Windows Logo" height="30">
                <div class="media-body">
                  <small>Get it from</small>
                  <h5>Microsoft Store</h5>
                </div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="copyright">Copyright © 2019 Mimity All right reserved</div>
    <!-- /Footer -->


    <!--Menu Modal -->
    <div class="modal modal-left modal-menu" id="menuModal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header shadow">
            <a class="h5 mb-0 d-flex align-items-center" href="index.html">
              <img src="/img/logo.svg" alt="Mimity" class="mr-3">
              <strong>Mimity</strong>
            </a>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body shadow">
            <ul class="menu" id="menu">
              <li class="no-sub"><a href="index.html"><i data-feather="home"></i> Home</a></li>
              <li>
                <a href="#" class="has-arrow"><i data-feather="shopping-bag"></i> Shop</a>
                <ul>
                  <li><a href="shop-categories.html">Shop Categories</a></li>
                  <li><a href="shop-grid.html">Shop Grid</a></li>
                  <li><a href="shop-list.html">Shop List</a></li>
                  <li><a href="shop-single.html">Single Product</a></li>
                  <li><a href="shop-single2.html">Single Product v2</a></li>
                  <li><a href="cart.html">Cart</a></li>
                  <li><a href="shipping.html">Checkout</a></li>
                  <li>
                    <a href="#">Submenu</a>
                    <ul>
                      <li><a href="javascript:void(0)">item #1</a></li>
                      <li><a href="javascript:void(0)">item #2</a></li>
                      <li><a href="javascript:void(0)">item #3</a></li>
                    </ul>
                  </li>
                </ul>
              </li>
              <li>
                <a href="#" class="has-arrow"><i data-feather="rss"></i> Blog</a>
                <ul>
                  <li><a href="blog-grid.html">Post Grid</a></li>
                  <li><a href="blog-list.html">Post List</a></li>
                  <li><a href="blog-single.html">Single Post</a></li>
                </ul>
              </li>
              <li>
                <a href="#" class="has-arrow"><i data-feather="user"></i> Account</a>
                <ul>
                  <li class="mm-active"><a href="account-login.html">Login / Register</a></li>
                  <li><a href="account-profile.html">Profile Page</a></li>
                  <li><a href="account-orders.html">Orders List</a></li>
                  <li><a href="account-order-detail.html">Order Detail</a></li>
                  <li><a href="account-wishlist.html" class="has-badge">Wishlist <span class="badge rounded badge-primary">2</span></a></li>
                  <li><a href="account-address.html">Address</a></li>
                </ul>
              </li>
              <li>
                <a href="#" class="has-arrow"><i data-feather="file"></i> Pages</a>
                <ul>
                  <li><a href="about.html">About Us</a></li>
                  <li><a href="contact.html">Contact Us</a></li>
                  <li><a href="compare.html">Compare</a></li>
                  <li><a href="faq.html">Help / FAQ</a></li>
                  <li><a href="404.html">404 Not Found</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- /Menu Modal -->


    <!-- REQUIRED JS  -->
    <script src="/plugins/jquery/jquery.min.js"></script>
    <script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/plugins/feather-icons/feather.min.js"></script>
    <script src="/plugins/metismenu/metisMenu.min.js"></script>
    <script src="/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>

    <!-- Mimity JS  -->
    <script src="/dist/js/script.min.js"></script>

    <script>
    $(function () {

      // Show reset password form
      $('.reset').click(function (event) {
        $('#row-login').attr('hidden', true)
        $('#row-reset').attr('hidden', false)
        event.preventDefault()
      })

      // Show login form
      $('.login').click(function (event) {
        $('#row-login').attr('hidden', false)
        $('#row-reset').attr('hidden', true)
        $('#row-reset-done').attr('hidden', true)
      })

      // Show reset password done message (demo purpose only)
      $('.reset-done').click(function (event) {
        $('#row-reset-done').attr('hidden', false)
        $('#row-reset').attr('hidden', true)
      })

    })
    </script>

  </body>
</html>