    <?php
      require_once("../templates/private/header.php");
    ?>
    <div class="wrapper">

    <?php
      require_once("../templates/private/topo.php");
    ?>

      <div class="dashboard">

    <?php
      require_once("../templates/private/menus.php");
    ?>      


        <!-- AQUI COMEÇA CONTEÚDO -->
        <div class="main">

          <div class="main__scroll scrollbar-macosx">
            <div class="main__cont">
              <!--
              <div class="main-heading">
                <div class="main-title">
                  <ol class="breadcrumb">
                    <li><a href="./">Dashboard</a></li>
                    <li class="active">Usuários</li>
                  </ol>
                </div>
                <div class="main-filter">
                  <form class="main-filter__search">
                    <div class="input-group">
                      <input class="form-control" type="text" placeholder="Busca...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button"><div class="fa fa-search"></div></button>
                        </span>
                    </div>
                  </form>
                </div>
              </div>
              <div class="container-fluid half-padding">
                <div class="datalist page page_users users float-right">
                  <div class="row">
                  <!--
                    <div class="col-sm-12 col-xs-12">
                      <div class="users-preview datalist-preview">
                        <div class="users-preview__cont">
                          <div class="users-preview__name" title="Name">Name</div>
                          <div class="users-preview__data">
                            <div class="users-preview__photo">
                              <div></div>
                            </div>
                            <div class="users-preview__info">
                              <div class="users-preview__position">Position</div>
                              <div class="users-preview__stat sparkline"></div>
                              <div class="users-preview__edit">
                                <div class="btn-group btn-group-sm">
                                  <button class="btn btn-danger" type="button">Editar</button>
                                  <button class="btn btn-danger dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></button>
                                  <ul class="dropdown-menu">
                                    <li><a href="#">Detalhes</a></li>
                                    <li><a href="#">Inativar</a></li>
                                  </ul>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div class="users-preview__props">
                            <div class="users-preview__prop" title="Location"><i class="fa fa-map-marker"></i><span class="users-preview__location">Location</span></div>
                            <div class="users-preview__prop" title="Contact"><i class="fa fa-envelope"></i><span class="users-preview__contact">Contact</span></div>
                            <div class="users-preview__prop"><i class="fa fa-calendar"></i><span class="users-preview__date">Date</span></div>
                            <div class="users-preview__prop"><i class="fa fa-heartbeat"></i><span class="users-preview__status">Status</span></div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- -->
                    
                    <div class="col-sm-12 col-xs-12">
                      <div class="panel panel-info">
                        <div class="panel-heading">
                          <h3 class="panel-title">Usuários</h3>
                        </div>
                        <div class="panel-body">
                          <p>Total de Usuários: <span id="int-total-usuarios">80</span></p>
                          <form class="datalist-filter">
                            <div class="input-group datalist-filter__search">
                              <input class="form-control" type="text" placeholder="Buscar Usuário"><span class="input-group-btn">
                                <button class="btn btn-default" type="button" role="button" data-toggle="collapse" data-target="#datalist-filter__detail" aria-controls="users__filter-detail" aria-expanded="false">
                                  <div class="fa fa-filter"></div>
                                </button></span>
                            </div>
                            <div class="collapse" id="datalist-filter__detail">
                              <div class="container-fluid datalist-filter__detail">
                                <div class="row">
                                  <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                    <div class="form-group">
                                      <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-map-marker"></i></div>
                                        <input class="form-control datalist-filter__location" type="text" placeholder="Location">
                                      </div>
                                    </div>
                                    <div class="form-group">
                                      <div class="input-group selectize__group">
                                        <div class="input-group-addon"><i class="fa fa-envelope-o"></i></div>
                                        <select class="datalist-filter__email" placeholder="Email"></select>
                                      </div>
                                    </div>
                                  </div>
                                  <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 input-daterange">
                                    <div class="form-group">
                                      <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-calendar-minus-o"></i></div>
                                        <input class="form-control datalist-filter__from" type="text" value="">
                                      </div>
                                    </div>
                                    <div class="form-group">
                                      <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-calendar-plus-o"></i></div>
                                        <input class="form-control datalist-filter__to" type="text" value="">
                                      </div>
                                    </div>
                                  </div>
                                  <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                    <div class="form-group">
                                      <input class="slider" id="datalist-filter__salary" type="text" name="" value="">
                                    </div>
                                    <div class="form-group">
                                      <div class="checkbox checkbox-danger">
                                        <input id="datalist-filter__actives" type="checkbox">
                                        <label for="datalist-filter__actives">Actives only</label>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </form>
                          <div class="datalist__result">
                            <ul class="nav nav-tabs" role="tablist">
                              <!--
                              <li class="active" role="presentation"><a href="#customers" aria-controls="customers" role="tab" data-toggle="tab">Clientes&nbsp;</a></li>
                              <li role="presentation"><a href="#managers" aria-controls="managers" role="tab" data-toggle="tab">Funcionários&nbsp;</a></li>
                              -->
                              <li class="active" role="presentation"><a href="#admins" aria-controls="admins" role="tab" data-toggle="tab">Admins&nbsp;</a></li>
                              <li role="presentation"><a href="#new" aria-controls="new" role="tab" data-toggle="tab"><i class="fa fa-plus"></i>&nbsp;Novo</a></li>
                            </ul>
                            <div class="tab-content">

                              <div class="tab-pane" id="new" role="tabpanel">

                                <!-- FORMULÁRIO DE CADASTRO DE USUÁRIO -->
                              
                                <?php require_once("../templates/private/usuarios/form-cadastro.php"); ?>

                                <!-- /FORMULÁRIO DE CADASTRO DE USUÁRIO -->

                              </div>
                              <!--
                              <div class="tab-pane active" id="customers" role="tabpanel">
                                <div class="scrollable scrollbar-macosx">
                                  <div class="container-fluid">
                                    <table class="datalist__table table datatable display table-hover" width="100%" data-users="customers">
                                      <thead>
                                        <tr>
                                          <th class="users__table-id">#ID</th>
                                          <th class="users__table-name">Nome</th>
                                          <th class="users__table-location">Localização</th>
                                          <th class="users__table-contact">Contato</th>
                                          <th class="users__table-date">Data</th>
                                          <th class="users__table-salary">Salário</th>
                                          <th></th>
                                          <th></th>
                                          <th class="users__table-status">Status</th>
                                        </tr>
                                      </thead>
                                    </table>
                                  </div>
                                </div>
                              </div>
                              <div class="tab-pane" id="managers" role="tabpanel">
                                <div class="scrollable scrollbar-macosx">
                                  <div class="container-fluid">
                                    <table class="datalist__table table datatable display table-hover" width="100%" data-users="managers">
                                      <thead>
                                        <tr>
                                          <th class="users__table-id">#ID</th>
                                          <th class="users__table-name">Name</th>
                                          <th class="users__table-location">Location</th>
                                          <th class="users__table-contact">Contact</th>
                                          <th class="users__table-date">Date</th>
                                          <th class="users__table-salary">Salary</th>
                                          <th></th>
                                          <th></th>
                                          <th class="users__table-status">Status</th>
                                        </tr>
                                      </thead>
                                    </table>
                                  </div>
                                </div>
                              </div>
                              -->
                              <div class="tab-pane" id="admins" role="tabpanel">
                                <div class="scrollable scrollbar-macosx">
                                  <div class="container-fluid">
                                    <table class="datalist__table table datatable display table-hover" width="100%" data-users="admins">
                                      <thead>
                                        <tr>
                                          <th class="users__table-id">#ID</th>
                                          <th class="users__table-name">Nome</th>
                                          <th class="users__table-location">Login</th>
                                          <th class="users__table-contact">E-mail</th>
                                          <th class="users__table-date">Nascto</th>
                                          <th class="users__table-salary">Salário</th>
                                          <th></th>
                                          <th></th>
                                          <th class="users__table-status">Status</th>
                                          <th class="users__table-actions">Ações</th>
                                        </tr>
                                      </thead>
                                    </table>
                                  </div>
                                </div>
                              </div>

                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <script src="libs/jquery/jquery.min.js"></script>
    <script src="libs/bootstrap/js/bootstrap.min.js"></script>
    <script src="libs/jquery.scrollbar/jquery.scrollbar.min.js"></script>
    <script src="libs/bootstrap-tabdrop/bootstrap-tabdrop.min.js"></script>
    <script src="libs/jquery-sparkline/jquery.sparkline.min.js"></script>
    <script src="libs/jquery.mask/jquery.mask.min.js"></script>
    <script src="libs/ionrangeslider/js/ion.rangeSlider.min.js"></script>
    <script src="libs/inputNumber/js/inputNumber.js"></script>
    <script src="libs/bootstrap-switch/js/bootstrap-switch.min.js"></script>
    <script src="libs/datatables/js/jquery.dataTables.js"></script>
    <script src="libs/datatables/js/dataTables.select.js"></script>
    <script src="libs/datatables/js/dataTables.bootstrap.js"></script>
    <script src="libs/selectize/js/standalone/selectize.min.js"></script>
    <script src="libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="libs/bootstrap-select/js/bootstrap-select.min.js"></script>
    <script src="js/template/users.js"></script>
    <script src="js/main.js"></script>
    <script src="js/demo.js"></script>

  </body>
</html>