<?php

  //var_dump( $data );
use Ajrc\Model\Caixa;

//----| VERIFICA SE HÁ CAIXA ABERTO |----
$result = Caixa::ListAll("COUNT(id) as total, c_nome_usuario_abertura, dh_abertura, valor_abertura", "WHERE status='A' LIMIT 1");
$temCaixaAberto = 0;
$usuarioQAbriu = null;
$dhAbertura = null;
$valorAbertura = null;
foreach($result as $caixa){
  $temCaixaAberto = $caixa->total;
  $usuarioQAbriu = $caixa->c_nome_usuario_abertura;
  $dhAbertura = $caixa->dh_abertura;
  $valorAbertura = number_format($caixa->valor_abertura,2,",",".");
}
//----

    require_once("../templates/private/header.php");
?>
    
    <div class="wrapper">

    <?php
      require_once("../templates/private/topo.php");
    ?>

      <div class="dashboard">

    <?php
      require_once("../templates/private/menus.php");
    ?>      

        <div class="main">

          <div class="main__scroll scrollbar-macosx">
            <div class="main__cont">
                    
                    <div class="col-sm-12 col-xs-12">
                      <div class="panel panel-info">
                        <div class="panel-heading">
                          <h1 class="panel-title h1">Caixa</h1>
                        </div>
                        <div class="panel-body">


                            <?php 
                                if(array_key_exists("form", $data))
                                {
                                    //----| EXIBE O RELATÓRIO DO CAIXA DO DIA |----
                                    if( $data["form"]=="report" )
                                    {

                                    }
                                    //----
                                }
                                else
                                {
                                    if(array_key_exists("message",$data)){ echo $data["message"]; } 
                                    if($temCaixaAberto==0)
                                    {

                                        //----| FORMULÁRIO DE ABERTURA DO CAIXA |----
                            ?>
                                        <form class="form users-new" data-toggle="validator" data-disable="false" role="form" method="POST" action="./caixa-abrir">
                                            <input type="hidden" name="uid" id="uid" value="<?php echo \Ajrc\Helper\Sessions::UserID(); ?>">
                                            <input type="hidden" name="operacao" value="open">
                                            
                                            <div class="form-group">
                                                <label for="inputName" class="control-label">VALOR DE ABERTURA</label>
                                                <input type="text" class="form-control form-control-lg" id="valor" name="valor" placeholder="Ex.: 200" required="">
                                            </div>
                                            
                                            <div class="form-group text-right">
                                                <button type="submit" class="btn btn-primary">ABRIR CAIXA</button>
                                            </div>
                                        </form>
                            <?php 
                                        //----
                                    }
                                    else
                                    {

                            ?>
                                  <hr>
                                  <div class="form-group text-center">
                                    <h1 style="color:#fff">CAIXA ABERTO</h1>
                                    <hr>
                                    <h4>Aberto por: <span style="color:#fff"><?php echo $usuarioQAbriu; ?></span></h4>
                                    <h4>Data de Abertura: <span style="color:#fff"><?php echo $dhAbertura; ?></span></h4>
                                    <h4>Valor de Abertura: <span style="color:#fff">R$ <?php echo $valorAbertura; ?></span></h4>
                                  </div>
                                  <hr>
                                  <div class="form-group text-center">
                                      <div class="row">
                                      <div class="col-xs-12 col-sm-6">
                                          <form class="form-inline" style="margin:10px 0"  data-toggle="validator" data-disable="false" role="form" method="POST" action="./caixa-fechar">
                                            <input type="hidden" name="uid" id="uid" value="<?php echo \Ajrc\Helper\Sessions::UserID(); ?>">
                                            <input type="hidden" name="operacao" value="close">
                                            <button type="button" class="btn btn-large btn-success btn-block">FECHAR CAIXA</button>
                                          </form>
                                      </div>
                                      <div class="col-xs-12 col-sm-6">
                                          <form class="form-inline my-5" style="margin:10px 0" data-toggle="validator" data-disable="false" role="form" method="POST" action="./caixa-report">
                                            <input type="hidden" name="uid" id="uid" value="<?php echo \Ajrc\Helper\Sessions::UserID(); ?>">
                                            <button type="button" class="btn btn-large btn-info btn-block">RELATÓRIO</button>
                                          </form>
                                      </div>
                                  </div>
                                

                            <?php   
                                    }
                                }
                            ?>
                        
                          
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
           
          </div>
        </div>


      </div>
    </div>
    
    <script src="libs/jquery/jquery.min.js"></script>
    <script src="libs/bootstrap/js/bootstrap.min.js"></script>
    <script src="libs/jquery.scrollbar/jquery.scrollbar.min.js"></script>
    <script src="libs/bootstrap-validator/validator.min.js"></script>
    <script src="libs/bootstrap-tabdrop/bootstrap-tabdrop.min.js"></script>
    <script src="libs/jquery-sparkline/jquery.sparkline.min.js"></script>
    <script src="libs/jquery.mask/jquery.mask.min.js"></script>
    <script src="libs/ionrangeslider/js/ion.rangeSlider.min.js"></script>
    <script src="libs/inputNumber/js/inputNumber.js"></script>
    <script src="libs/bootstrap-switch/js/bootstrap-switch.min.js"></script>
    <script src="libs/datatables/js/jquery.dataTables.js"></script>
    <script src="libs/datatables/js/dataTables.select.js"></script>
    <script src="libs/datatables/js/dataTables.bootstrap.js"></script>
    <script src="libs/selectize/js/standalone/selectize.min.js"></script>
    <script src="libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="libs/bootstrap-select/js/bootstrap-select.min.js"></script>
    <script src="js/template/contas.js"></script>
    <script src="js/main.js"></script>



  </body>
</html>