<?php

use Ajrc\Helper\Sessions;
use Ajrc\Model\Carrinho;

$id_carrinho = trim($_POST["cid"]);
$rs = Ajrc\Config\ConfigBoletoFacil::getPaymentCreditCard();

// SEO : SEARCH ENGINE OPTIMIZATE ----
$title = "Chokoart :: Pedido realizado com sucesso!";
$description = $title." - BoletoFacil!";
$url_redirect = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
//----

require_once("../templates/public/header.php");
require_once("../templates/public/topo.php");

?>

    <!-- Main Content -->
    <div class="container my-3">

        <div class="card">
            <div class="card-header bg-white border-bottom flex-center p-0">
                <ul class="nav nav-pills card-header-pills main-nav-pills" role="tablist">
                    <li class="nav-item"><a class="nav-link" href="#"><small>Carrinho</small></a></li>
                    <li class="nav-item"><a class="nav-link disabled" href="javascript:void(0)"><i data-feather="arrow-right"></i></a></li>
                    <li class="nav-item"><a class="nav-link" href="#"><small>Entrega</small></a></li>
                    <li class="nav-item"><a class="nav-link disabled" href="javascript:void(0)"><i data-feather="arrow-right"></i></a></li>
                    <li class="nav-item"><a class="nav-link " href="#"><small>Formas Pagamento</small></a></li>
                    <li class="nav-item"><a class="nav-link disabled" href="javascript:void(0)"><i data-feather="arrow-right"></i></a></li>
                    <li class="nav-item"><a class="nav-link active" href="#">FINALIZAÇÃO</a></li>
                </ul>
            </div>

            <!-- Main Content -->
            <div class="card">
                <div class="card-body">
                    <div class="text-center py-3">
                    <i data-feather="check-circle" class="text-success" width="48" height="48"></i>
                    <h1>Obrigado por comprar na Chokoart!</h1>
                    <p>Seu pedido foi realizado com sucesso e está em processo de análise.<br>E o mais breve possível o enviaremos.</p>
                    <p>Enviamos um e-mail de confirmação para <u><?php echo trim($_POST['email']); ?></u></p>
                    <hr>
                    
                    <p class="mb-0">
                        <span class="text-muted">CÓDIGO DO PEDIDO: </span>
                        <span class="text-info"><?php echo $rs["codigopedido"]; ?></span>
                        <br>
                        <span class="text-muted">Frete e Prazo de Entrega*: </span>
                        <span class="text-info"><?php echo $_POST['modalidade_frete']; ?> - <?php echo $_POST['prazo_entrega']." Dia(s)"; ?></span>
                        <br>
                        <span class="text-muted">Endereço de Entrega: </span>
                        <span class="text-info"><?php echo trim($_POST['endereco']).", ".trim($_POST['numero'])." - ".trim($_POST['complemento'])." - ".trim($_POST['bairro'])." - ".trim($_POST['cidade'])." - ".trim($_POST['estado']); ?></span>
                    </p>
                    <hr>
                    <p class="mb-0">
                        <span class="text-muted">Itens: </span>
                        <span class="text-info">
                        <table class="table table-borderless table-cart" data-addclass-on-smdown="table-sm">
                        <tbody id="tbody_cart_itens_list">
                        <?php Carrinho::GetPublicListFinishOrder($id_carrinho); ?>
                        </tbody>
                        </table>
                        </span>
                    </p>
                    <p class="mb-0">
                        <span class="text-muted">Valor dos Itens:** </span>
                        <span class="text-info">R$ <?php echo number_format(trim($_POST['amount']-$_POST['valor_frete']),2,",","."); ?></span>
                        <span class="text-muted ml-md-4">Valor Frete: </span>
                        <span class="text-info">R$ <?php echo number_format($_POST['valor_frete'],2,",","."); ?></span>
                        <span class="text-muted ml-md-4">Valor Total: </span>
                        <span class="text-info">R$ <?php echo number_format($_POST['amount'],2,",","."); ?></span>
                    </p>
                    
                    <p class="mb-0">
                        <span class="text-muted">Forma de Pagamento: </span>
                        <span class="text-info">
                        <?php 
                            if(trim($_POST["forma_pagto"])=="boleto"){ echo "Boleto Bancário"; } 
                            else{ echo "Cartão de Crédito em ".trim($_POST['installments'])." x R\$ ".number_format(trim($_POST['totalAmount']),2,",",".")." = R\$ ".number_format($_POST['amount'],2,",","."); }
                        ?>
                        </span>
                    </p>
                    
                    <a href="#" class="btn btn-default rounded-pill btn-lg mt-4">Ver meus Pedidos</a>
                    <a href="./zs" class="btn btn-primary rounded-pill btn-lg mt-4">VOLTAR A PÁGINA PRINCIPAL</a>
                    </div>
                </div>
            </div>
            <!-- /Main Content -->

        </div>

    </div>
    <!-- /Main Content -->

<!-- Footer -->
<?php 
require_once("../templates/public/footer.php"); 
?>
<!-- /Footer -->

<script src="./plugins/jquery/jquery.min.js"></script>
<script src="./plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="./plugins/feather-icons/feather.min.js"></script>
<script src="./plugins/metismenu/metisMenu.min.js"></script>
<script src="./plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script src="./dist/js/script.min.js"></script>


<script>

    $(function () {
        App.atwDemo() // Add to Wishlist Demo
        <?php
            if(Sessions::UserID()!="") { 
                //echo "WishList.Persistence('./add-whislist');"; 
            }
            echo "Armazenamento.Del('cart_list'); ClientCart.SetItens();";
        ?>

    })
</script>
