<?php

use Ajrc\Helper\Sessions;
use Ajrc\Helper\AlertBootstrap4 as Alert;
use Ajrc\Model\Destaque;
use Ajrc\Model\Produto;
use Ajrc\Config\ConfigBoletoFacil as BoletoFacil;

$usuario_id = trim($_POST['uid']);
$id_sessao = session_id();
$_POST["id_sessao"] = $id_sessao;
$id_carrinho = trim($_POST['id_carrinho']);
$cpfcnpj = trim($_POST['cpfcnpj']);
$valor_total_pedido = trim($_POST['valor_total_pedido']);
$valor_total_pedido_sem_frete = trim($_POST['valor_total_pedido_sem_frete']);
$nome = trim($_POST['nome']);
$email = trim($_POST['email']);
$cep = trim($_POST['cep']);
$estado = trim($_POST['estado']);
$cidade = trim($_POST['cidade']);
$bairro = trim($_POST['bairro']);
$endereco = trim($_POST['endereco']);
$numero = trim($_POST['numero']);
$complemento = trim($_POST['complemento']);

$nCdServico = trim($_POST['nCdServico']);
$prazo_entrega = trim($_POST["prazo_entrega"]);
$modalidade_frete = trim($_POST["tipo_entrega"]);

$total_produtos = COUNT($_POST["produtos_id"]);
$inputs_hidden_produtos_id = null;
$inputs_hidden_qtde_produtos = null;
for($i=0;$i<$total_produtos;$i++) {
    $inputs_hidden_produtos_id.= "<input type='hidden' name='produtos_id[]' value='".trim($_POST["produtos_id"][$i])."'>";
    $inputs_hidden_qtde_produtos.= "<input type='hidden' name='qtde[]' value='".trim($_POST["qtde"][$i])."'>";
}

//----| CÁLCULO DAS PARCELAS PARA O CARTÃO |----
$numParcelas = 12;
$acrescimoApartir = 2;
$porcentAcrescimo = 1.00;
$optsParcelas = null;
$optValorTotalPedido = $valor_total_pedido;
$optValorParcela = $valor_total_pedido;
$optStrComJuros = null;
$optsParcelas = '<option value="" selected>Selecione o número de parcelas</option>';
for($i=1;$i<=$numParcelas;$i++) {
    if($i>$acrescimoApartir){ $porcentAcrescimo = 1.0379+($i*0.0001); $optStrComJuros = ' <small style="font-size:10px">- com juros</small>'; }
    $optValorTotalPedido = number_format(round(($valor_total_pedido*$porcentAcrescimo),2),2,'.',',');
    $optValorParcela = number_format(round(($optValorTotalPedido/$i),2),2,'.',',');
    $optsParcelas.= '<option value="'.$i.'-'.number_format($optValorParcela,2,'.',',').'">'.$i.' x R$ '.number_format($optValorParcela,2,',','.').' ( R$ '.number_format($optValorParcela*$i,2,',','.').' ) '.$optStrComJuros.'</option>';
}
//----

// SEO : SEARCH ENGINE OPTIMIZATE ----
$title = "Chokoart :: Formas de Pagamento!";
$description = $title." - BoletoFacil!";
$url_redirect = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
//----

require_once("../templates/public/header.php");
require_once("../templates/public/topo.php");

?>

    <!-- Main Content -->
    <div class="container my-3">

        <div class="card">
            <div class="card-header bg-white border-bottom flex-center p-0">
                <ul class="nav nav-pills card-header-pills main-nav-pills" role="tablist">
                    <li class="nav-item"><a class="nav-link" href="#"><small>Carrinho</small></a></li>
                    <li class="nav-item"><a class="nav-link disabled" href="javascript:void(0)"><i data-feather="arrow-right"></i></a></li>
                    <li class="nav-item"><a class="nav-link" href="#"><small>Entrega</small></a></li>
                    <li class="nav-item"><a class="nav-link disabled" href="javascript:void(0)"><i data-feather="arrow-right"></i></a></li>
                    <li class="nav-item"><a class="nav-link active" href="#">FORMAS DE PAGAMENTO</a></li>
                    <li class="nav-item"><a class="nav-link disabled" href="javascript:void(0)"><i data-feather="arrow-right"></i></a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Finalização</a></li>
                </ul>
            </div>
            
            <div class="card-body pt-5 flex-center flex-column">

                <form class="form-style-1" id="form-payment" method="POST" action="./cart">
                    <?php echo $inputs_hidden_produtos_id . $inputs_hidden_qtde_produtos; ?> 
                    <input type="hidden" name="cid"                 id="cid"                value="<?php echo $id_carrinho; ?>">
                    <input type="hidden" name="uid"                 id="uid"                value="<?php echo $usuario_id; ?>">
                    <input type="hidden" name="id_sessao"           id="id_sessao"          value="<?php echo $id_sessao; ?>">
                    <input type="hidden" name="amount"              id="amount"             value="<?php echo $valor_total_pedido; ?>">
                    <input type="hidden" name="nome"                id="nome"               value="<?php echo $nome; ?>">
                    <input type="hidden" name="email"               id="email"              value="<?php echo $email; ?>">
                    <input type="hidden" name="cpfcnpj"             id="cpfcnpj"            value="<?php echo $cpfcnpj; ?>">
                    <input type="hidden" name="cep"                 id="cep"                value="<?php echo $cep; ?>">
                    <input type="hidden" name="estado"              id="estado"             value="<?php echo $estado; ?>">
                    <input type="hidden" name="cidade"              id="cidade"             value="<?php echo $cidade; ?>">
                    <input type="hidden" name="bairro"              id="bairro"             value="<?php echo $bairro; ?>">
                    <input type="hidden" name="endereco"            id="endereco"           value="<?php echo $endereco; ?>">
                    <input type="hidden" name="numero"              id="numero"             value="<?php echo $numero; ?>">
                    <input type="hidden" name="complemento"         id="complemento"        value="<?php echo $complemento; ?>">
                    <input type="hidden" name="modalidade_frete"                            value="<?php echo $modalidade_frete; ?>">
                    <input type="hidden" name="prazo_entrega"                               value="<?php echo $prazo_entrega; ?>">
                    <input type="hidden" name="valor_frete"                                 value="<?php echo $nCdServico; ?>">
                    <input type="hidden" name="installments"        id="installments"       value="">
                    <input type="hidden" name="totalAmount"         id="totalAmount"        value="">
                    <input type="hidden" name="creditCardHash"      id="creditCardHash"     value="">
                    <input type="hidden" name="forma_pagto"                                 value="creditCard">
                    <input type="hidden" name="passo"               id="passo"              value="4">
                    <h2 class="roboto-condensed text-center">CARTÃO DE CRÉDITO</h2>
                    <h6 class="text-muted mb-4 text-center">tenha em mãos o seu Cartão de Crédito!</h6>
                    <div class='card-wrapper mb-3'></div>
                    <div class="form-group">
                    <input type="text" id="txtCardNumber" name="number" class="form-control" placeholder="Número do Cartão" required>
                    </div>
                    <div class="form-group">
                    <input type="text" id="txtCardName" name="name" class="form-control" placeholder="Nome escrito no Cartão" value="" required>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-sm-6">
                            <input type="text" id="txtCardExpiry" name="expiry" class="form-control" placeholder="Válido até" required>
                        </div>
                        <div class="form-group col-sm-6">
                            <input type="text" id="txtCardCvv" name="cvc" class="form-control" placeholder="Código CVV" required>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-sm-12">
                            <select class="form-control custom-select" id="numParcelas" name="numParcelas" required>
                                <?php echo $optsParcelas; ?>
                            </select>
                        </div>
                    </div>
                    <div class="text-center">
                        <small class="counter">SUBTOTAL</small>
                        <h3 class="roboto-condensed bold" id="h3TotalPedido">R$ <?php echo number_format($valor_total_pedido,2,',','.'); ?></h3>
                        <button id="btnFinalizarPedido" type="submit" class="btn btn-primary rounded-pill btn-lg">FINALIZAR PEDIDO COM CARTÃO</button>
                    </div>
                </form>
            </div>

            <div id="divFormasPagto" class="card-body flex-center flex-column">
                <h2 class="roboto-condensed mb-4 text-center">OU</h2>
                <div id="containerBoleto" style="text-center center">
                    <form class="form-style-1" id="form-payment-boleto" method="POST" action="./cart">
                        <?php echo $inputs_hidden_produtos_id . $inputs_hidden_qtde_produtos; ?> 
                        <input type="hidden" name="cid"                 value="<?php echo $id_carrinho; ?>">
                        <input type="hidden" name="uid"                 value="<?php echo $usuario_id; ?>">
                        <input type="hidden" name="id_sessao"           value="<?php echo $id_sessao; ?>">
                        <input type="hidden" name="amount"              value="<?php echo $valor_total_pedido; ?>">
                        <input type="hidden" name="nome"                value="<?php echo $nome; ?>">
                        <input type="hidden" name="email"               value="<?php echo $email; ?>">
                        <input type="hidden" name="cpfcnpj"             value="<?php echo $cpfcnpj; ?>">
                        <input type="hidden" name="cep"                 value="<?php echo $cep; ?>">
                        <input type="hidden" name="estado"              value="<?php echo $estado; ?>">
                        <input type="hidden" name="cidade"              value="<?php echo $cidade; ?>">
                        <input type="hidden" name="bairro"              value="<?php echo $bairro; ?>">
                        <input type="hidden" name="endereco"            value="<?php echo $endereco; ?>">
                        <input type="hidden" name="numero"              value="<?php echo $numero; ?>">
                        <input type="hidden" name="complemento"         value="<?php echo $complemento; ?>">
                        <input type="hidden" name="modalidade_frete"    value="<?php echo $modalidade_frete; ?>">
                        <input type="hidden" name="prazo_entrega"       value="<?php echo $prazo_entrega; ?>">
                        <input type="hidden" name="valor_frete"         value="<?php echo $nCdServico; ?>">
                        <input type="hidden" name="installments"        value="1">
                        <input type="hidden" name="totalAmount"         value="<?php echo $valor_total_pedido; ?>">
                        <input type="hidden" name="forma_pagto"         value="boleto">
                        <input type="hidden" name="passo"               value="3">
                        <button id="btnFinalizarPedidoBoleto" type="submit" class="btn btn-default"><?php echo '<strong>FINALIZAR PEDIDO COM<BR>BOLETO BANCÁRIO<br><small>(será acrescentado o valor de R$ 1,00 ao boleto)<small></strong><br><object type="image/svg+xml" data="img/logo_boleto_facil.svg" width="60" height="60"></object>'; ?></button>
                        </form>
                </div>
            </div>

            <div id="resultado"></div>

        </div>

    </div>
    <!-- /Main Content -->

<!-- Footer -->
<?php 
require_once("../templates/public/footer.php"); 
?>
<!-- /Footer -->

<script src="./plugins/jquery/jquery.min.js"></script>
<script src="./plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="./plugins/feather-icons/feather.min.js"></script>
<script src="./plugins/metismenu/metisMenu.min.js"></script>
<script src="./plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script src="./plugins/card/jquery.card.min.js"></script>
<script src="./dist/js/script.min.js"></script>


<script src="<?php echo BoletoFacil::getUrlJS(); ?>"></script>
<script>

    $(function () {

        $('#form-payment').card({container: '.card-wrapper'})
        
        <?php
        //----| SÓ MOSTRARÁ OS DADOS ABAIXO SE O USUÁRIO ESTIVAR LOGADO EM SUA CONTA |----
        if(Sessions::UserID()!="") 
        { 
        ?>
            /* Em sandbox utilizar o construtor new DirectCheckout('SEU TOKEN PUBLICO', false); */
            var checkout = new DirectCheckout('<?php echo BoletoFacil::getMyPublicCreditCardToken(); ?>',false);
            var naok = 0;
            const AjrcBoletoFacilAux = { installments:0, totalAmount:0.00, amount:0.00 }
            const AjrcBoletoFacil = {bandeira:'',cardNumber:'',holderName:'',securityCode:'',expirationMonth:'',expirationYear:''};
            $('input#txtCardNumber').blur(function(){ 
                AjrcBoletoFacil.cardNumber = $("input#txtCardNumber").val().replace(" ","").replace(" ","").replace(" ","").replace(" ","")
                AjrcBoletoFacil.bandeira = checkout.getCardType(AjrcBoletoFacil.cardNumber);
                if(!checkout.isValidCardNumber(AjrcBoletoFacil.cardNumber)){ naok++; }
                $('input#txtCardName').blur(function(){
                    AjrcBoletoFacil.holderName = $('input#txtCardName').val().trim()
                    $('input#txtCardExpiry').blur(function(){
                        var dataExp = $("input#txtCardExpiry").val().trim().split("/")
                        AjrcBoletoFacil.expirationMonth = dataExp[0].trim();
                        AjrcBoletoFacil.expirationYear = dataExp[1].trim();
                        if(!checkout.isValidExpireDate(AjrcBoletoFacil.expirationMonth, AjrcBoletoFacil.expirationYear)){ naok++; }
                        $('input#txtCardCvv').blur(function(){
                            AjrcBoletoFacil.securityCode = $("input#txtCardCvv").val().trim();
                            if(!checkout.isValidSecurityCode(AjrcBoletoFacil.cardNumber, AjrcBoletoFacil.securityCode)){ naok++; }
                            checkout.getCardHash(AjrcBoletoFacil, function(cardHash) { AjrcBoletoFacil.cardHash = cardHash; /*$('select#numParcelas').removeAttr("disabled");*/ console.log("naook: ", naok, " | cardHash: ", AjrcBoletoFacil.cardHash, AjrcBoletoFacil.cardNumber, AjrcBoletoFacil.bandeira, AjrcBoletoFacil.expirationMonth, AjrcBoletoFacil.expirationYear, AjrcBoletoFacil.securityCode); }, function(error) { console.log(error); naok++; });
                        })
                    })
                })
            })
            
            $('select#numParcelas').change(function(){
                if($('select#numParcelas').val().trim()!="") {
                    var vals = $('select#numParcelas').val().trim().split("-")
                    AjrcBoletoFacilAux.installments = vals[0];
                    AjrcBoletoFacilAux.totalAmount = vals[1];
                    AjrcBoletoFacilAux.amount = parseFloat(AjrcBoletoFacilAux.totalAmount*AjrcBoletoFacilAux.installments).toFixed(2);
                    $("h3#h3TotalPedido").html('R$ '+parseFloat(AjrcBoletoFacilAux.amount).toFixed(2).replace(".",","))
                    $("input#installments").val(AjrcBoletoFacilAux.installments)
                    $("input#totalAmount").val(AjrcBoletoFacilAux.totalAmount)
                    $("input#amount").val(AjrcBoletoFacilAux.amount)
                    $("input#creditCardHash").val(AjrcBoletoFacil.cardHash)
                    console.log("naook: ", naok, " | cardHash: ", AjrcBoletoFacil.cardHash, AjrcBoletoFacil.cardNumber, AjrcBoletoFacil.bandeira, AjrcBoletoFacil.expirationMonth, AjrcBoletoFacil.expirationYear, AjrcBoletoFacil.securityCode);
                }
            })
            
            $("form#form-payment").submit(function(ev){
                $("button#btnFinalizarPedido").html("Enviando ... ")
                $("button#btnFinalizarPedido").attr("disabled",true)
                $("button#btnFinalizarPedidoBoleto").attr("disabled",true)
            })
            
            $("form#form-payment-boleto").submit(function(ev){
                $("button#btnFinalizarPedido").html("Enviando ... ")
                $("button#btnFinalizarPedido").attr("disabled",true)
                $("button#btnFinalizarPedidoBoleto").attr("disabled",true)
            })
            

        <?php 
        }
        //----
        ?>

        

    })
</script>
