    <?php

      use Ajrc\Helper\Sessions;
      use Ajrc\Helper\AlertBootstrap4 as Alert;
      use Ajrc\Model\Destaque;
      
      require_once("../templates/public/header.php");
      require_once("../templates/public/topo.php");

    ?>
    <!-- Main Content -->

    <!-- Home slider -->
    <?php 
      Destaque::GetPrincipal(); 
    ?>
    <!-- /Home slider -->

    <div class="container mt-3">

      <!-- Top Categories 1 -->
      <?php
        Destaque::GetSecondary();
      ?>
      <!-- /Top Categories 1 -->

      <!-- Discover --

      <div class="text-center mt-3">
        <a href="./categorias" class="btn btn-light border rounded-pill bold text-muted">VEJA TODAS CATEGORIAS</a>
      </div>

      <div class="row categories-grid gutters-3 mt-gutter">

        <div class="col-sm-6 col-md-4">
          <a href="shop-grid.html">
            <div class="card zoom-hover">
              <div data-cover="../img/discover/1.jpeg" data-xs-height="150px" data-sm-height="272px" data-md-height="246px" data-lg-height="324px" data-xl-height="400px"></div>
              <div class="card-img-overlay card-img-overlay-transparent">
                <h2 class="card-title bold">NEW ARRIVALS</h2>
              </div>
            </div>
          </a>
        </div>

        <div class="col-sm-6 col-md-4">
          <div class="row gutters-3">
            <div class="col-6 col-sm-12 mt-3 mt-sm-0">
              <a href="shop-grid.html">
                <div class="card zoom-hover">
                  <div data-cover="../img/discover/2.jpeg" data-xs-height="100px" data-sm-height="128px" data-md-height="115px" data-lg-height="154px" data-xl-height="192px"></div>
                  <div class="card-img-overlay card-img-overlay-transparent">
                    <h3 class="card-title text-center">Crossbody Bag</h3>
                  </div>
                </div>
              </a>
            </div>
            <div class="col-6 col-sm-12 mt-3">
              <a href="shop-grid.html">
                <div class="card zoom-hover">
                  <div data-cover="../img/discover/3.jpeg" data-xs-height="100px" data-sm-height="128px" data-md-height="115px" data-lg-height="154px" data-xl-height="192px"></div>
                  <div class="card-img-overlay card-img-overlay-transparent">
                    <h3 class="card-title text-center">Winter Collection</h3>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="row gutters-3">
            <div class="col-6 col-md-12 mt-3 mt-md-0">
              <a href="shop-grid.html">
                <div class="card zoom-hover">
                  <div data-cover="../img/discover/4.jpeg" data-xs-height="100px" data-sm-height="128px" data-md-height="115px" data-lg-height="154px" data-xl-height="192px"></div>
                  <div class="card-img-overlay card-img-overlay-transparent">
                    <h2 class="card-title text-center">Accessories</h2>
                  </div>
                </div>
              </a>
            </div>
            <div class="col-6 col-md-12 mt-3">
              <a href="shop-grid.html">
                <div class="card zoom-hover">
                  <div data-cover="../img/discover/5.jpeg" data-xs-height="100px" data-sm-height="128px" data-md-height="115px" data-lg-height="154px" data-xl-height="192px"></div>
                  <div class="card-img-overlay card-img-overlay-transparent">
                    <h2 class="card-title text-center">Hats</h2>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </div>

        <a href="shop-grid.html" class="btn btn btn-light shadow-sm sa-btn">Descubra <i data-feather="arrow-right"></i></a>

      </div>
      <-- /Discover -->

      <h4 class="bold text-center mt-gutter">Nossos Produtos</h4>

      <!-- Featured Products -->
      <div class="grid grid-gap-3 grid-col-md-4 my-3">

            <div class="card card-product">
              <div class="card-body">
                <button class="wishlist atw-demo" title="Add to wishlist" id="<?php echo Sessions::UserID(); ?>-1"><i data-feather="heart"></i></button>
                <a href="shop-single.html"><img class="card-img-top" src="./img/produtos/1_0.jpg" alt="Card image cap"></a>
                <a href="shop-single.html" class="card-title">Hanes Hooded Sweatshirt</a>
                <span class="badge badge-success">Lançamento!</span>
                <span class="badge badge-danger">20% OFF</span>
                <div class="price">
                  <span class="h5 del">R$ 19,00</span>
                  <span class="h5">R$ 15,00</span>
                </div>
                <div class="color-options">
                  <label class="custom-control custom-radio custom-radio-color custom-control-inline">
                    <input type="radio" name="color-option2" class="custom-control-input" value="./img/produtos/1_0.jpg" checked>
                    <span class="custom-control-label" style="background-color: transparent"><i data-feather="image"></i></span>
                  </label>
                  <label class="custom-control custom-radio custom-radio-color custom-control-inline">
                    <input type="radio" name="color-option2" class="custom-control-input" value="./img/produtos/1_1.jpg">
                    <span class="custom-control-label" style="background-color: transparent"><i data-feather="image"></i></span>
                  </label>
                  <label class="custom-control custom-radio custom-radio-color custom-control-inline">
                    <input type="radio" name="color-option2" class="custom-control-input" value="./img/produtos/1_2.jpg">
                    <span class="custom-control-label" style="background-color: transparent"><i data-feather="image"></i></span>
                  </label>
                </div>
              </div>
              <div class="card-footer">
                <button class="btn btn-sm rounded-pill btn-outline-primary btn-block atc-demo">Adicionar ao <i data-feather="shopping-cart"></i></button>
              </div>
            </div>

        
      </div>
      <!-- /Featured Products -->

      <div class="text-center mt-3">
        <a href="./todos-produtos" class="btn btn-light border rounded-pill bold text-muted">VEJA TODOS NOSSOS PRODUTOS</a>
      </div>

    </div>
    <!-- /Main Content -->

    <!-- Footer -->
    <?php 
    require_once("../templates/public/footer.php"); 
    ?>
    <!-- /Footer -->

    <!-- REQUIRED JS  -->
    <script src="plugins/jquery/jquery.min.js"></script>
    <script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="plugins/feather-icons/feather.min.js"></script>
    <script src="./plugins/metismenu/metisMenu.min.js"></script>
    <script src="./plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <!-- PLUGINS FOR CURRENT PAGE -->
    <script src="./plugins/swiper/swiper.min.js"></script>
    <script src="./plugins/noty/noty.min.js"></script>
    <script src="./plugins/jquery-countdown/jquery.countdown.min.js"></script>

    <!-- Mimity JS  -->
    <script src="./dist/js/script.min.js"></script>
    <script>
    $(function () {

      App.atcDemo() // Add to Cart Demo
      App.atwDemo() // Add to Wishlist Demo
      App.homeSlider('#home-slider')
      App.colorOption() //Change Product Colors

    })
    </script>

  </body>
</html>
