    <?php

      use Ajrc\Helper\Sessions;
      use Ajrc\Helper\AlertBootstrap4 as Alert;
      use Ajrc\Model\Destaque;
      use Ajrc\Model\Produto;
      
      require_once("../templates/public/header.php");
      require_once("../templates/public/topo.php");

    ?>
    <!-- Main Content -->

    <!-- Home slider -->
    <?php 
      Destaque::GetPrincipal(); 
    ?>
    <!-- /Home slider -->

    <div class="container mt-3">

      <!-- Top Categories 1 -->
      <?php
        Destaque::GetSecondary();
      ?>
      <!-- /Top Categories 1 -->

      <!-- Discover --

      <div class="text-center mt-3">
        <a href="./categorias" class="btn btn-light border rounded-pill bold text-muted">VEJA TODAS CATEGORIAS</a>
      </div>

      <div class="row categories-grid gutters-3 mt-gutter">

        <div class="col-sm-6 col-md-4">
          <a href="shop-grid.html">
            <div class="card zoom-hover">
              <div data-cover="../img/discover/1.jpeg" data-xs-height="150px" data-sm-height="272px" data-md-height="246px" data-lg-height="324px" data-xl-height="400px"></div>
              <div class="card-img-overlay card-img-overlay-transparent">
                <h2 class="card-title bold">NEW ARRIVALS</h2>
              </div>
            </div>
          </a>
        </div>

        <div class="col-sm-6 col-md-4">
          <div class="row gutters-3">
            <div class="col-6 col-sm-12 mt-3 mt-sm-0">
              <a href="shop-grid.html">
                <div class="card zoom-hover">
                  <div data-cover="../img/discover/2.jpeg" data-xs-height="100px" data-sm-height="128px" data-md-height="115px" data-lg-height="154px" data-xl-height="192px"></div>
                  <div class="card-img-overlay card-img-overlay-transparent">
                    <h3 class="card-title text-center">Crossbody Bag</h3>
                  </div>
                </div>
              </a>
            </div>
            <div class="col-6 col-sm-12 mt-3">
              <a href="shop-grid.html">
                <div class="card zoom-hover">
                  <div data-cover="../img/discover/3.jpeg" data-xs-height="100px" data-sm-height="128px" data-md-height="115px" data-lg-height="154px" data-xl-height="192px"></div>
                  <div class="card-img-overlay card-img-overlay-transparent">
                    <h3 class="card-title text-center">Winter Collection</h3>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="row gutters-3">
            <div class="col-6 col-md-12 mt-3 mt-md-0">
              <a href="shop-grid.html">
                <div class="card zoom-hover">
                  <div data-cover="../img/discover/4.jpeg" data-xs-height="100px" data-sm-height="128px" data-md-height="115px" data-lg-height="154px" data-xl-height="192px"></div>
                  <div class="card-img-overlay card-img-overlay-transparent">
                    <h2 class="card-title text-center">Accessories</h2>
                  </div>
                </div>
              </a>
            </div>
            <div class="col-6 col-md-12 mt-3">
              <a href="shop-grid.html">
                <div class="card zoom-hover">
                  <div data-cover="../img/discover/5.jpeg" data-xs-height="100px" data-sm-height="128px" data-md-height="115px" data-lg-height="154px" data-xl-height="192px"></div>
                  <div class="card-img-overlay card-img-overlay-transparent">
                    <h2 class="card-title text-center">Hats</h2>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </div>

        <a href="shop-grid.html" class="btn btn btn-light shadow-sm sa-btn">Descubra <i data-feather="arrow-right"></i></a>

      </div>
      <-- /Discover -->

      <h4 class="bold text-center mt-gutter">Nossos Produtos</h4>

      <div class="text-center mt-3">
        <a href="./todos-produtos" class="btn btn-light border rounded-pill bold text-muted">VEJA TODOS NOSSOS PRODUTOS</a>
      </div>

      <!-- Featured Products -->
      <div class="grid grid-gap-3 grid-col-md-4 my-3">

        <?php Produto::GetPublicAll(); ?>
        
      
      <!-- /Featured Products -->
    </div>
    <!-- /Main Content -->
    

    <!-- Footer -->
    <?php 
    require_once("../templates/public/footer.php"); 
    ?>
    <!-- /Footer -->

    <!-- REQUIRED JS  -->
    <script src="plugins/jquery/jquery.min.js"></script>
    <script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="plugins/feather-icons/feather.min.js"></script>
    <script src="./plugins/metismenu/metisMenu.min.js"></script>
    <script src="./plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="./plugins/swiper/swiper.min.js"></script>
    <script src="./plugins/noty/noty.min.js"></script>
    <script src="./plugins/jquery-countdown/jquery.countdown.min.js"></script>
    <script src="./dist/js/script.min.js"></script>
    <script>
 
    $(function () {

      App.atcDemo() // Add to Cart Demo
      App.atwDemo() // Add to Wishlist Demo
      App.homeSlider('#home-slider')
      App.colorOption() //Change Product Colors
      <?php
        if(Sessions::UserID()!="") { 
          echo "WishList.Persistence('./add-whislist');"; 
        }
      ?>
      
    })

    </script>

  </body>
</html>
