CREATE VIEW `vw_produtos` AS SELECT
tp.id,
tp.tb_fornecedores_id,
tp.tb_usuarios_id,
tp.tb_categorias_id,
tp.titulo,
tp.qtde_atual,
tp.qtde_ideal,
tp.peso,
tp.unidade_medida,
tp.preco_custo,
tp.preco_venda,
tp.observacoes,
tp.descritivo,
tp.data_cadastro,
tp.status,
tp.ncm,
tp.codigo,
(SELECT titulo FROM tb_categorias WHERE id=tp.tb_categorias_id) as categoria,
(SELECT nome_fantasia FROM tb_fornecedores WHERE id=tp.tb_fornecedores_id) as fornecedor,
(SELECT nome FROM tb_usuarios WHERE id=tp.tb_usuarios_id) as cadastrante,
(SELECT (tp.preco_venda - tp.preco_custo)) as lucro,
(SELECT IF((tp.qtde_atual > tp.qtde_ideal),'SUFICIENTE','INSUFICIENTE')) as situacao,
(SELECT (tp.qtde_atual * tp.preco_custo)) as custo_estoque,
(SELECT (tp.qtde_atual * (tp.preco_venda - tp.preco_custo))) as lucro_estoque
FROM 
	tb_produtos tp